export const siteConfig = {
  name: 'NVNM Chain Docs',
  description: 'NVNM Chain anchors cryptographic hashes generated by Inveniam IO, enabling the verification and provenance of private market asset data.',
  url: 'https://docs.nvnmchain.io',
  logo: {
    light: '/logo/nvnm-logo-primary.svg',
    dark: '/logo/nvnm-logo-primary.svg',
    alt: 'NVNM Chain',
    width: 120,
    height: 40,
  },
  links: {
    github: 'https://github.com/NVNM-Chain/nvnmchain-tempo'
  },
  footer: {
    companyName: 'Inveniam IO',
    links: [
      { label: 'Inveniam', href: 'https://inveniam.io' },
      { label: 'Inveniam Hub', href: 'https://hub.inveniam.io' },
      { label: 'GitHub', href: 'https://github.com/NVNM-Chain/nvnmchain-tempo' },
    ],
  },
  navbar: {
    primaryButton: {
      label: 'NVNM Hub',
      href: 'https://hub.inveniam.io',
    },
  },
  banner: {
    content: 'nvnm-tempo-devnet-1 is a NEW and Experimental L1 - a standalone EVM DevNet forked from Tempo.  Endpoints and services may be unstable or unusable and the chain may be reset from time-to-time.',
    dismissible: false,
  },
}

// Pre-release channel palette. The `next` docs use violet in both modes so the
// site reads as "not production" at a glance, while production docs keep the
// NVNM brand blue. Amber stays reserved for instability warnings (site banner,
// warning callouts) so those still stand out against the accent.
//
// These values are mirrored in app/globals.css, which is what actually renders
// the theme. __tests__/lib/theme-config.test.ts fails if the two drift apart.
export const themeConfig = {
  colors: {
    light: {
      accent: '#7C3AED',
      accentForeground: '#ffffff',
      accentMuted: 'rgba(124, 58, 237, 0.08)',
    },
    dark: {
      accent: '#A78BFA',
      accentForeground: '#12101A',
      accentMuted: 'rgba(167, 139, 250, 0.14)',
    },
  },
  codeBlock: {
    light: {
      background: '#fafafa',
      titleBar: '#f3f4f6',
    },
    dark: {
      background: '#1a1a1f',
      titleBar: '#1f2937',
    },
  },
  ogImage: {
    gradient: 'linear-gradient(135deg, #ffffff 0%, #e8f0ff 50%, #0055FF22 100%)',
    titleColor: '#0f172a',
    sectionColor: '#0055FF',
    logoUrl: 'https://docs.nvnmchain.io/logo/dark.avif',
  },
}

export function getCSSVariables(mode: 'light' | 'dark') {
  const colors = themeConfig.colors[mode]
  return {
    '--accent': colors.accent,
    '--accent-foreground': colors.accentForeground,
    '--accent-muted': colors.accentMuted,
  }
}

export function getSiteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) {
    return process.env.NEXT_PUBLIC_SITE_URL
  }
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`
  }
  return siteConfig.url
}
