export const siteConfig = {
  name: 'NVNM Chain Docs',
  description: 'NVNM Chain anchors cryptographic hashes generated by Inveniam IO, enabling the verification and provenance of private market asset data.',
  url: 'https://docs.nvnmchain.io',
  logo: {
    light: '/logo/light.avif',
    dark: '/logo/dark.avif',
    alt: 'NVNM Chain',
    width: 120,
    height: 40,
  },
  links: {
    github: 'https://github.com/NVNM-Chain/nvnmchain',
    twitter: 'https://x.com/nvnmchain',
    linkedin: 'https://linkedin.com/company/inveniam',
    support: 'mailto:contact@nvnmchain.io',
  },
  footer: {
    companyName: 'Inveniam IO',
    links: [
      { label: 'Inveniam', href: 'https://inveniam.io' },
      { label: 'Inveniam Hub', href: 'https://hub.inveniam.io' },
      { label: 'GitHub', href: 'https://github.com/NVNM-Chain/nvnmchain' },
    ],
  },
  navbar: {
    primaryButton: {
      label: 'NVNM Hub',
      href: 'https://hub.inveniam.io',
    },
  },
  // banner: {
  //   content: '⚠️ NVNM Chain Testnet `nvnm-testnet-1` Genesis is IN PROGRESS. Endpoints and services may be unstable or unusable until genesis is complete.',
  //   dismissible: false,
  // },
}

export const themeConfig = {
  colors: {
    light: {
      accent: '#0055FF',
      accentForeground: '#ffffff',
      accentMuted: 'rgba(0, 85, 255, 0.1)',
    },
    dark: {
      accent: '#07C983',
      accentForeground: '#0f172a',
      accentMuted: 'rgba(7, 201, 131, 0.1)',
    },
  },
  codeBlock: {
    light: {
      background: '#fafafa',
      titleBar: '#f3f4f6',
    },
    dark: {
      background: '#1a1a1f',
      titleBar: '#1f2937',
    },
  },
  ogImage: {
    gradient: 'linear-gradient(135deg, #ffffff 0%, #e8f0ff 50%, #0055FF22 100%)',
    titleColor: '#0f172a',
    sectionColor: '#0055FF',
    logoUrl: 'https://docs.nvnmchain.io/logo/light.avif',
  },
}

export function getCSSVariables(mode: 'light' | 'dark') {
  const colors = themeConfig.colors[mode]
  return {
    '--accent': colors.accent,
    '--accent-foreground': colors.accentForeground,
    '--accent-muted': colors.accentMuted,
  }
}

export function getSiteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) {
    return process.env.NEXT_PUBLIC_SITE_URL
  }
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`
  }
  return siteConfig.url
}
